#Password Generation
import random
import string

temp =[]
User = input("Enter your name: ")

upper1=random.choice(string.ascii_letters)
upper2=random.choice(string.ascii_letters)
upper1=upper1.upper()
upper2=upper2.upper()

lower1=random.choice(string.ascii_letters)
lower2=random.choice(string.ascii_letters)
lower1=lower1.lower()
lower2=lower1.lower()

num1 = random.randint(0,9)
num2 = random.randint(0,9)

c='[@_!#$%^&*()<>?/\|}{~:]'
for i in c:
  temp.append(i)
random.shuffle(temp)

Password=upper2+upper1+lower2+lower1+str(num2)+str(num1)+temp[0]+temp[1]

Password_Ref = print(f"{User} Here is the password generated by the system {Password}")
Satisfies = input("Are you okay with the password generated by system : ")
if Satisfies =="No":
  print("you can create your own password Thank you ")
  
else:
  print(f"Thank You {User}")
  
if Satisfies =="No":
  s = input("PlEASE ENTER YOUR PASSWORD: ")
  c='[@_!#$%^&*()<>?/\|}{~:]'
  Upper = 0
  Lower = 0
  Number = 0
  length = len(s)
  spl_case = 0
  for i in c:
    for j in s:
      if i ==j:
        spl_case=spl_case+1     
  for i in s:
    for i in s:
        if i.islower() ==True :
          Lower=Lower+1
        if i.isupper() ==True:
          Upper= Upper+1
        if i.isnumeric() ==True:
          Number= Number+1    
  if Upper>=1 and Lower>=1 and Number>=1 and length>=8 and spl_case>=1:
    print("Your Password is Perfect")
  if Upper==0:
    print("invalid!! atleast one uppercase required")
  if Lower==0:
    print("invalid!! atleast one lowercase required")
  if Number==0:
    print("invalid!! atleast one number required ") 
  if length <8:
    print("invalid!! password must contain min 8 char")   
  if spl_case ==0:
    print("invalid!! atleast one spl Char required")
  if Upper==0 or Lower==0 or Number==0 or length <8 or spl_case ==0:
    print("ReEnter the password"+input())

